name: Send Message

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 * * * *'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Execute Python script
        run: python main.py
        env:
          BOT_API: ${{ secrets.BOT_API }}
          G_ID: ${{ secrets.G_ID }}